tab_spaces = 2
max_width = 100
array_width = 60
match_arm_leading_pipes = 'Always'
merge_imports = true
newline_style = 'Unix'
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 32

ignore = ['./target']
